# Dependabot will run on day 21 of each month at 03:22 (Europe/Berlin timezone)
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "22 3 21 * *"
    open-pull-requests-limit: 20
    assignees:
      - "foxthefox"
    versioning-strategy: "increase"
